name: PillDaddy
options:
  bundleIdPrefix: com.pilldaddy
settings:
  base:
    DEVELOPMENT_TEAM: 6HQGHHRK87
    ENABLE_USER_SCRIPT_SANDBOXING: YES
    STRING_CATALOG_GENERATE_SYMBOLS: YES
    ASSETCATALOG_COMPILER_GENERATE_SWIFT_ASSET_SYMBOL_EXTENSIONS: YES
targets:
  PillDaddy:
    type: application
    platform: iOS
    deploymentTarget: "26.0"
    sources:
      - PillDaddy
    info:
      path: PillDaddy/Info.plist
      properties:
        UILaunchScreen:
          StoryboardName: ""
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
        ITSAppUsesNonExemptEncryption: false
        UIRequiresFullScreen: true
        UIBackgroundModes:
          - remote-notification
        NSSupportsLiveActivities: true
        CFBundleURLTypes:
          - CFBundleURLSchemes:
              - pilldaddy

    settings:
      base:
        CODE_SIGN_ENTITLEMENTS: PillDaddy/PillDaddy.entitlements
    dependencies:
      - target: PillDaddyWidgets
        embed: true
  PillDaddyTests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: "26.0"
    sources:
      - PillDaddyTests
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
    dependencies:
      - target: PillDaddy
  PillDaddyWidgets:
    type: app-extension
    platform: iOS
    deploymentTarget: "26.0"
    sources:
      - PillDaddyWidgets
      - path: PillDaddy/Shared
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.pilldaddy.PillDaddy.widgets
    info:
      path: PillDaddyWidgets/Info.plist
      properties:
        CFBundleDisplayName: PillDaddy Reminders
        NSExtension:
          NSExtensionPointIdentifier: com.apple.widgetkit-extension
schemes:
  PillDaddy:
    build:
      targets:
        PillDaddy: all
        PillDaddyTests: [test]
        PillDaddyWidgets: all
    run:
      debugEnabled: false
    test:
      targets:
        - PillDaddyTests

